---
title: "temperaturelacleman"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{temperaturelacleman}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

```{r setup}
library(temperaturelacleman)
```

```{r, eval=FALSE}
# Request the data
request_data <- temperaturelacleman:::get_data_from_alplakes()
```

*Using recorded data for vignette.*
```{r}
request_data <- temperaturelacleman::alplakes_call20250415
```


```{r}
# Clean data
clean_alpdata <- temperaturelacleman:::clean_alplakes_data(request_data)
```

```{r}
# Format the tables
tables_to_plot <- temperaturelacleman:::create_alplakes_tables(clean_alpdata)

```

## example 1 jour court
```{r}
# print data
tables_to_plot[["small_show_table_day"]][[1]]|>
  temperaturelacleman:::create_gt_alplakes_table()
```

## example 1 jour long
```{r}
tables_to_plot[["long_show_table_day"]][[1]] |>
  temperaturelacleman:::create_gt_alplakes_table()
```

## example semaine
```{r}
tables_to_plot[["small_show_table"]] |>
  temperaturelacleman:::create_gt_alplakes_table()
```

