globalVariables(c("bs_theme",
                  "card",
                  "card_body",
                  "card_footer",
                  "card_header",
                  "nav_panel",
                  "page_navbar",
                  "profondeur",
                  "."))
